name: Generator

on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"
          architecture: "x64"
      - name: Get Python version
        run: python -V

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python generator.py
        env:
          ENV: "GithubAction"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BASE_BRANCH: "master"
          REF_BRANCH: "develop"
      - name: Run Python (Deck)
        run: python generator.py
        env:
          ENV: "GithubAction"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BASE_BRANCH: "master"
          REF_BRANCH: "develop"
          CLIENT_TYPE: Deck
          OUTPUT_DIR: docs/deck
